// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('add task', function() {
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('add task', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1552, height: 840 })
    await driver.findElement(By.linkText("Add")).click()
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.id("title")).sendKeys("task 1")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("this is a test for Selenium")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("Tasks")).click()
  })
})
